onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - nestjs-pino
  - nice-napi
  - prisma
  - unrs-resolver
